spring.application.name=simulador
spring.datasource.url=jdbc:mysql://localhost:3306/urjc?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# OpenRouteService API
ors.api.key=${ORS_API_KEY:5b3ce3597851110001cf624862ddbae857554fdb9da5e7279b8d6656}